# Generated by Django 5.1.4 on 2025-01-06 10:33

import send_contact_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('send_contact_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(send_contact_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
    ]
