# Generated by Django 5.1.4 on 2024-12-30 08:57

import notification_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='manager',
            field=models.ForeignKey(on_delete=models.SET(notification_app.models.get_sentinel_user), related_name='manager_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
