# Generated by Django 5.1.5 on 2025-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品合計金額'),
        ),
    ]
