# Generated by Django 5.1.4 on 2025-01-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_rename_transactions_transaction_alter_order_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='worker_id',
            new_name='worker',
        ),
    ]
