# Generated by Django 5.1.4 on 2025-01-07 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0003_rename_transactions_transaction_alter_order_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_group', models.CharField(max_length=1, verbose_name='送信者の属性')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='メッセージ送信時間')),
                ('text', models.CharField(max_length=150, verbose_name='メッセージ文')),
                ('read_flag', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='client_app.task', verbose_name='チャット')),
            ],
        ),
    ]
